
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - BASH_SHELLCHECK
  - REPOSITORY_KICS

YAML_YAMLLINT_ARGUMENTS: "-d {extends: relaxed, rules: {line-length: {max: 105}}}"
YAML_YAMLLINT_COMMAND_REMOVE_ARGUMENTS: "-c .yamllint.yml"
REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
