
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT

DISABLE_ERRORS_LINTERS:
  - MAKEFILE_CHECKMAKE
  - REPOSITORY_KICS
  - BASH_SHELLCHECK

FILTER_REGEX_EXCLUDE: (vendor/)