name: "setup-trestle"
description: "Composite action to setup trestle."

inputs:
  python-version:
     required: false
     description: "The python version to use"
     default: "3.11"

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: make trestle-install
      shell: bash