name: Evaluate OSCAL content
on:
  pull_request:
    types: [ opened, review_requested, ready_for_review, reopened, synchronize ]
    branches:
      - main
jobs:
  release:
    name: Evaluate OSCAL content
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Validate with Trestle
        run: make validate
