name: Regenerate component definition content
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'
      - 'component-definitions/**'

jobs:
  update:
    name: Regenerate content
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Regenerate component definitions
        id: regenerate
        uses: RedHatProductSecurity/trestle-bot@main
        with:
          markdown_path: "markdown/components"
          oscal_model: "compdef"
          file_pattern: "markdown/*"
          branch: "autoupdate-${{ github.run_id }}"
          target_branch: "main"
          skip_assemble: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      