name: Transform Rules On Push

# Only run on pushes to branches other than main. Pushes to main should be
# a result of a pull request merge. The transform rules operation is not idempotent
# and the OSCAL JSON will be modified each time it is run.
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'rules/**'

jobs:
  call-transform:
    uses: ./.github/workflows/transform-rules.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit